name: food_order_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  d_info: ^0.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  simple_animations: ^5.0.2
  url_launcher: ^6.3.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
